### ISSUE TITLE
How to make it run with self-managed Splunk Enterprise 

### ISSUE THREAD

**Issue by Dentrax** [splunk/splunk-cloud-sdk-go#364]
I'm struggling to run Hello World example as in showed in the README file:

```
client, err := sdk.NewClient(&services.Config{
  Token: os.Getenv("BEARER_TOKEN"),
  Host:  "splunk.example.com",
})
```

But it returns an error:

```
Get "https://api.splunk.example.com//identity/v3/validate?include=principal%2Ctenant": dial tcp: lookup api.splunk.example.com: no such host
```

SDK automatically add `api.` prefix in the host. I can access the Splunk Dashboard on `splunk.example.com`.

```
$ curl -s -o /dev/null -w "%{http_code}" https://splunk.example.com -L
200

$ curl -s -o /dev/null -w "%{http_code}" https://api.splunk.example.com
000
```

I inspected most network requests and noticed those are not use `api.` prefix. All of requests something like:

```
https://splunk.example.com/en-US/splunkd/__raw/services/...
```

I also don't know the TENANT value. Is there any easy way to learn this on self-managed Splunk?

At the end of the day, I have a `$BEARER_TOKEN`, `$HOST` and want to send a simple query such as `index=foo` and get the response eventually.

Any thoughts on this? Thanks!

**Comment by tdhellmann** [comment]
It's a relatively common request - you can upvote it here: https://ideas.splunk.com/ideas/DTID-I-15
